import json

class RiskManager:
    def __init__(self):
        pass

    def assess_risk(self, signal: dict, market_data: dict, news_summary: str, ai_callback) -> dict:
        """
        Critiques the provided trading signal using a second AI call.
        
        Args:
            signal: The trade signal dictionary generated by the Strategy Agent.
            market_data: The market data dictionary.
            news_summary: A string summary of recent news.
            ai_callback: A function with signature (prompt, system_prompt) -> str.
            
        Returns:
            A dictionary containing the risk assessment.
        """
        
        # Construct the prompt
        system_prompt = (
            "You are a conservative Risk Manager for a crypto trading desk. "
            "Your job is to critique trading signals generated by a Strategy Agent. "
            "You must be skeptical and look for reasons NOT to take the trade. "
            "Consider market structure, recent news, and the quality of the signal's reasoning.\n\n"
            "Output MUST be a JSON object with keys: "
            "'approved' (boolean), 'risk_score' (1-10, 10 is highest risk), "
            "'modified_conviction' (optional int, suggested new score), "
            "'critique' (string explanation)."
        )
        
        user_prompt = (
            f"Please review the following Trade Signal:\n{json.dumps(signal, indent=2)}\n\n"
            f"Market Context:\n- Price: {market_data.get('value', 'N/A')}\n"
            f"- Liquidity: {market_data.get('liquidity', 'N/A')}\n"
            f"- 24h Volume: {market_data.get('volume', 'N/A')}\n\n"
            f"News Context:\n{news_summary}\n\n"
            "Assess the risk. If the news is negative but the signal is LONG, reject or heavily penalize. "
            "If the signal reasoning is weak, reject. "
            "If the risk/reward is poor, reject."
        )
        
        # Call the AI
        response_text = ai_callback(user_prompt, system_prompt)
        
        # Parse response
        try:
            # Handle potential markdown code blocks
            if "```json" in response_text:
                json_str = response_text.split("```json")[1].split("```")[0].strip()
            elif "```" in response_text:
                json_str = response_text.split("```")[1].split("```")[0].strip()
            else:
                json_str = response_text.strip()
                
            assessment = json.loads(json_str)
            return assessment
            
        except Exception as e:
            return {
                "approved": False,
                "risk_score": 10,
                "critique": f"Risk Manager failed to parse AI response: {str(e)}. Raw response: {response_text[:100]}..."
            }
